### ISSUE TITLE
Updated package keyring

### ISSUE THREAD

**Issue by kelleyk** [JAremko/spacemacs-circleci#2]
Hello!

I maintain the PPA (https://launchpad.net/~kelleyk/+archive/ubuntu/emacs) that your CI uses to install Emacs.  I just wanted to let you know that I've released new packages (version `25.3~2`) that include the updated keyring.  It looks like you've changed your Dockerfiles to update the keyring after installation, which should no longer be necessary (but also shouldn't hurt anything).

Feel free to let me know if you have issues with the packages in the future; I [track issues on GitHub](https://github.com/kelleyk/ppa-emacs/issues).

**Comment by JAremko** [comment]
@kelleyk  Thanks for the heads up  :wink:
